### ISSUE TITLE
Does not work with CRA

### ISSUE THREAD

**Issue by danizord** [austintgriffith/eth-hooks#172]
Steps to reproduce:

1. `npx create-react-app test-eth-hooks`
2. cd `test-eth-hooks`
3. `yarn add eth-hooks`
4. Add `<EthersAppContext>` to `src/index.js`
5. `yarn start`

Result: 

>ERROR in ./node_modules/eth-hooks/chunk-4XVGVTT5.js 32:0-40
Module not found: Error: Can't resolve 'react/jsx-runtime

**Comment by ShravanSunder** [comment]
## eth-hooks v4 uses esm
which version of react-scripts are you using?  

### react scripts v5
it does not work with v5 due to issues it has with common js.  they have to fix them.
- https://github.com/facebook/create-react-app/issues/11769
- https://github.com/facebook/react/issues/20235
- https://github.com/facebook/create-react-app/discussions/11278#discussioncomment-1208359

### with react scripts v4
- use browserlist to last 10 browsers: https://github.com/scaffold-eth/scaffold-eth/blob/hooks-v4-staging/packages/react-app/package.json
- use react-app-polyfill
