### ISSUE TITLE
leadingTrigger on useExchangeEthPrice

### ISSUE THREAD

**Issue by carletex** [austintgriffith/eth-hooks#242]
Would it be possible to add a `leadingTrigger: true` here?

https://github.com/scaffold-eth/eth-ui/blob/8d65ac4c9a9a29a0d6407ff8ad7b6a9a8263b21d/src/dapps/dex/useExchangeEthPrice.ts#L41

Check this conversation for context: https://github.com/scaffold-eth/scaffold-eth/pull/896#issuecomment-1262712820

**Comment by ShravanSunder** [comment]
@carletex i haven't looked at v2 in a while.  It was done over a year ago.  I'm not sure what the side effects.
There was bunch of difficulties with that hook, that's why everything was changed for v3 and v4.  

Feel free to add it, there should be a v2 branch, you can make a PR and made the modifications.  
if you make the changes, tenst and merge to v2 branch i'll be happy to deploy to npm.  I can also give you access to npm package.

**Comment by ShravanSunder** [comment]
@carletex  v2 new version has been published:  https://www.npmjs.com/package/eth-hooks/v/2.3.18

**Comment by carletex** [comment]
Tysm @ShravanSunder !!
